### ISSUE TITLE
Create a script that handles the case-sensitive search and replace on the theme files

### ISSUE THREAD

**Issue by braican** [Upstatement/skela-wp-theme#35]
# Summary

Instead of requiring the developer to do a case-sensitive search and replace for references to the `Skela` name in the theme, it would be nice to have a script that we can run to do that for us.

## Basic example

Say I want to name the new theme `Upstatement`. Perhaps during the `./bin/install` script we have a prompt for the new theme name that would run the search and replace on the theme files, replacing all references of the `skela` name with `upstatement`. We'd probably want three different prompts - one for the all lowercase references, one for the all uppercase references, and one for the title-case references.

## Motivation

Manually doing search-and-replace operations, especially on case-sensitive ones, can be prone to errors and takes time during the developer's setup.

**Comment by bchiang7** [comment]
Addressed with #37
